# docker-compose build --build-arg USER_ID=$(id -u)   --build-arg GROUP_ID=$(id -g)
version: '3'
services:
  app:
    build: ./box/php
    volumes:
      - .:/var/www/html/
    working_dir: /var/www/html/
