name: PHP Composer

on:
  push:
    branches: [ master, 2.0.x ]
  pull_request:
    branches: [ master, 2.0.x ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - 8.1
          - 8.0
          - 7.4

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: CS fix
      run: vendor/bin/php-cs-fixer fix ./src/ --dry-run

    - name: Run test suite
      run: composer coverage

    - name: Run coverage threshold >= 75%
      run: php coverage-checker.php ./clover.xml 75
